{"status": "Compile Error", "problem_id": 1001, "language": "tobylang-cpp", "username": "toby_lai@126.com", "code": "create int:n\r\ncreate int:m\r\ncreate int:r\r\nset n=intinput(\"\")\r\nset m=intinput(\"\")\r\nset r=n+m\r\nprint(r)", "msg": "Traceback (most recent call last):\n  File \"/usr/bin/tobylang/tobylang.py\", line 134, in <module>\n    group_run()\n  File \"/usr/lib/python3/dist-packages/click/core.py\", line 764, in __call__\n    return self.main(*args, **kwargs)\n  File \"/usr/lib/python3/dist-packages/click/core.py\", line 717, in main\n    rv = self.invoke(ctx)\n  File \"/usr/lib/python3/dist-packages/click/core.py\", line 1137, in invoke\n    return _process_result(sub_ctx.command.invoke(sub_ctx))\n  File \"/usr/lib/python3/dist-packages/click/core.py\", line 956, in invoke\n    return ctx.invoke(self.callback, **ctx.params)\n  File \"/usr/lib/python3/dist-packages/click/core.py\", line 555, in invoke\n    return callback(*args, **kwargs)\n  File \"/usr/bin/tobylang/tobylang.py\", line 60, in compile_\n    if detect_gpp(compiler):\n  File \"/usr/bin/tobylang/tobylang.py\", line 28, in detect_gpp\n    p = subprocess.Popen(f\"{exe} -v\", stdout=subprocess.PIPE, stderr=subprocess.STDOUT)\n  File \"/usr/lib/python3.8/subprocess.py\", line 858, in __init__\n    self._execute_child(args, executable, preexec_fn, close_fds,\n  File \"/usr/lib/python3.8/subprocess.py\", line 1704, in _execute_child\n    raise child_exception_type(errno_num, err_msg, err_filename)\nFileNotFoundError: [Errno 2] No such file or directory: '/usr/bin/g++ -v'\n"}